export const BUSINESS_INFO = {
  name: "NOA Croissant",
  legalName: "NOA Croissant Alanya",
  siteUrl: "https://www.noacroissant.com",
  canonicalDomain: "www.noacroissant.com",
  description: {
    tr: "Alanya’da taze kruvasanlar, özel tatlılar, kahve çeşitleri ve kahvaltı seçenekleri. NOA Croissant menüsünü inceleyin ve masanızdan sipariş verin.",
    en: "Fresh artisan croissants, specialty desserts, coffees, and breakfast options in Alanya. Explore the NOA Croissant menu and order from your table.",
    de: "Frische handgemachte Croissants, Desserts, Kaffeespezialitäten und Frühstück in Alanya. Entdecken Sie das NOA Croissant Menü.",
    ru: "Свежие ремесленные круассаны, авторские десерты, кофе и завтраки в Аланье. Меню NOA Croissant и заказ со столика.",
    nl: "Verse ambachtelijke croissants, desserts, koffiespecialiteiten en ontbijt in Alanya. Bekijk het NOA Croissant menu.",
    sv: "Färska hantverkscroissanter, desserter, specialkaffe och frukost i Alanya. Utforska NOA Croissant-menyn.",
    no: "Ferske håndverkskroissanter, desserter, spesialkaffe og frokost i Alanya. Utforsk NOA Croissant-menyen.",
    fi: "Tuoreet artesaanicroissantit, erikoisjälkiruoat, kahvit ja aamiaiset Alanyassa. Tutustu NOA Croissant -menuun.",
    pl: "Świeże rzemieślnicze rogaliki croissant, desery, kawy i śniadania w Alanyi. Sprawdź menu NOA Croissant.",
    ar: "كرواسون طازج، حلويات مميزة، قهوة مختصة وخيارات فطور في ألانيا. تصفح قائمة طعام NOA Croissant واطلب من طاولتك.",
  },
  address: {
    streetAddress: "Saray, Yunus Emre Cd.",
    addressLocality: "Alanya",
    addressRegion: "Antalya",
    postalCode: "07400",
    addressCountry: "TR",
    formatted: "Saray, Yunus Emre Cd., 07400 Alanya/Antalya",
  },
  telephone: "+905404233307",
  displayPhone: "+90 540 423 33 07",
  openingHours: "09:30 – 00:00",
  openingHoursDays: "Pazartesi - Pazar / Her Gün (Monday - Sunday / Every Day)",
  openingHoursSpecification: [
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday",
      ],
      opens: "09:30",
      closes: "00:00",
    },
  ],
  geo: {
    latitude: 36.5458,
    longitude: 31.9897,
  },
  social: {
    instagram: "https://www.instagram.com/noacroissant/",
    instagramHandle: "@noacroissant",
    googleMapsCid: "11614042030776745743",
    googleMapsUrl: "https://maps.google.com/?cid=11614042030776745743",
    googleMapsEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3204.8516086877994!2d31.9871251!3d36.5458!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14dca3a802c5d407%3A0xa12d5db172e77f0f!2sNOA%20Croissant!5e0!3m2!1str!2str!4v1700000000000",
  },
  priceRange: "₺₺",
  currenciesAccepted: "TRY",
  paymentAccepted: "Nakit, Kredi Kartı, Temassız (Cash, Credit Card, Contactless)",
  servesCuisine: [
    "French",
    "Bakery",
    "Desserts",
    "Specialty Coffee",
    "Breakfast",
  ],
  schemaTypes: ["Bakery", "CafeOrCoffeeShop", "Restaurant"],
};
